# Generated by Django 4.2.5 on 2023-10-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "preferencia_evento",
                    models.CharField(
                        choices=[
                            ("todos", "Todos"),
                            ("consulta", "Consultas"),
                            ("exame", "Exames"),
                            ("paciente", "Pacientes"),
                        ],
                        default="todos",
                        max_length=20,
                        verbose_name="Solicitação",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "enviado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "modificado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
            ],
        ),
    ]
